config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root controller: :articles, action: :index
  resources :articles, only: [:new, :create, :show] do 
    resources :comments, only: [:create]
  end
  resources :subscriptions, only: [:new, :create]
 end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    has_many :comments
    validates :title, presence: true
    #validates :content, presence: true, message: 'WTF man?'
    validates_presence_of :content, message: 'WTF man?'
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :article
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
  end

  def create
    article = Article.create(article_params)
    if article.persisted?
      flash[:success] = 'Your article was successfully created'
      redirect_to root_path
    else
      flash[:error] = article.errors.full_messages.first
      render :new
    end
  end

  def show
    @article = Article.find(params[:id])
  end

  private
  def article_params
    params.require(:article).permit(:title, :content)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    article = Article.find(params[:article_id])
    #Comment.create(body: params[:comment][:body], article_id: article.id)
    #Comment.create(comments_params.merge({article_id: params[:article_id]}))
    article.comments.create(comments_params)
    flash[:success] = 'Thank you for your feedback'
    redirect_to article_path(article)
  end

  private
  def comments_params
    params.require(:comment).permit(:body, :email)
  end

end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  def create
    customer = Stripe::Customer.create(
      email: params[:stripeEmail],
      source: params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      customer: customer.id,
      amount: 10000,
      description: 'My news service subscription',
      currency: 'sek'
    )

    if charge.paid? 
      current_user.update_attribute(:subscriber, true)
      flash_message = 'Welcome as a subscriber!'
    else
      flash_message = 'That did not work....'
    end
    redirect_to root_path, notice: flash_message
  end

  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/index.html.haml
= link_to "Become subscriber", new_subscription_path
- @articles.each do |article|
    %h1= link_to article.title, article_path(article)
    %p= article.content
= link_to 'Create Article', new_article_path

app/views/articles/new.html.haml
= form_with model: @article do |form|
    = form.label :title
    = form.text_field :title
    = form.label :content
    = form.text_field :content
    = form.submit value: 'Save'

app/views/articles/show.html.haml
%h1= @article.title
%p= @article.content

= form_with scope: :comment, url: article_comments_path(@article) do |form|
    = form.label :body
    = form.text_area :body
    = form.label :email
    = form.email_field :email
    = form.submit

- if @article.comments.any? 
    - @article.comments.each do |comment|
        %p= comment.body
        %p= "Submitted by: #{comment.email}"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AutDemoApril</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |key, value|%>
      <p><%= value %></p>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/subscriptions/new.html.haml
%h1 Subscription page 
= form_with url: subscriptions_path, local: true do 
    %script.stripe-button{src: 'https://checkout.stripe.com/checkout.js',
    data: {amount: 10000,
    description: "News Service Subscription",
    currency: "sek",
    email: "#{current_user.email if current_user}",
    key: 'pk_test_QicERB8w3kyqaYW3hUUQylRH'}}